server:
  port: 8082

spring:
  application:
    name: commande-service
  datasource:
    url: jdbc:mysql://localhost:3306/commande?useSSL=false
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

