server:
  port: 8889

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    produit-service:
      path: /produits/**
      service-id: produit-service
    commande-service:
      path: /commandes/**
      service-id: commande-service
