server:
  port: 8889

spring:
  application:
    name: gateway-service

zuul:
  prefix: /api
  routes:
    commande:
      path: /commande/**
      serviceId: commande-service
    produit:
      path: /produit/**
      serviceId: produit-service
ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    registerWithEureka: true
