server:
  port: 8889

spring:
  application:
    name: gateway-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    registerWithEureka: true
